-- MCCNO Executive Dashboard - DAX Measures
-- Generated from project specifications
-- Date: 2025-08-21 06:46:18

-- ===============================
-- PRIMARY KPI MEASURES
-- ===============================

GMROI = 
DIVIDE(
    SUM(Sales[gross_margin]), 
    AVERAGE(Inventory[qty] * Inventory[cost]), 
    0
)

Total_Revenue = SUM(Sales[revenue])

Sell_Through_Rate = 
DIVIDE(
    SUM(Sales[units_sold]), 
    SUM(Inventory[qty]), 
    0
)

Days_of_Supply = 
DIVIDE(
    SUM(Inventory[qty]), 
    CALCULATE(
        AVERAGE(Sales[units_sold]), 
        DATESINPERIOD(Date[date], TODAY(), -30, DAY)
    ), 
    0
)

-- ===============================
-- EVENT IMPACT MEASURES
-- ===============================

Event_Revenue = 
CALCULATE(
    SUM(Sales[revenue]), 
    NOT(ISBLANK(Sales[event_id]))
)

Event_Conversion_Rate = 
DIVIDE(
    [Event_Revenue] / AVERAGE(Sales[price]), 
    RELATED(Events[est_attendance]), 
    0
)

Pre_Event_Inventory = 
CALCULATE(
    SUM(Inventory[qty]), 
    DATEADD(Events[start_dt], -7, DAY)
)

Post_Event_Inventory = 
CALCULATE(
    SUM(Inventory[qty]), 
    DATEADD(Events[end_dt], 3, DAY)
)

-- ===============================
-- RISK & ALERT MEASURES
-- ===============================

Stockout_Risk_SKUs = 
CALCULATE(
    DISTINCTCOUNT(Inventory[sku]), 
    Inventory[qty] < Inventory[reorder_point]
)

Critical_Stock_Level = 
CALCULATE(
    DISTINCTCOUNT(Inventory[sku]), 
    [Days_of_Supply] < 7
)

Shrink_Variance_Percent = 
DIVIDE(
    ABS([Expected_Inventory] - [Actual_Inventory]), 
    [Expected_Inventory], 
    0
)

-- ===============================
-- FINANCIAL MEASURES
-- ===============================

Gross_Margin_Percent = 
DIVIDE(
    SUM(Sales[gross_margin]), 
    SUM(Sales[revenue]), 
    0
)

Inventory_Value = 
SUMX(Inventory, Inventory[qty] * Inventory[cost])

-- ===============================
-- TIME INTELLIGENCE MEASURES
-- ===============================

Revenue_YTD = 
TOTALYTD(SUM(Sales[revenue]), Date[date])

Revenue_Previous_Month = 
CALCULATE(
    SUM(Sales[revenue]), 
    DATEADD(Date[date], -1, MONTH)
)

Revenue_Growth_Percent = 
DIVIDE(
    [Total_Revenue] - [Revenue_Previous_Month], 
    [Revenue_Previous_Month], 
    0
)

-- ===============================
-- CALCULATED COLUMNS
-- ===============================

-- Add to Sales table:
-- Margin_Percent = DIVIDE(Sales[gross_margin], Sales[revenue], 0)

-- Add to Inventory table:
-- Inventory_Value = Inventory[qty] * Inventory[cost]
-- Stock_Status = IF(Inventory[qty] <= Inventory[reorder_point], "Reorder", IF(Inventory[qty] <= Inventory[safety_stock], "Critical", "Normal"))

-- Add to Events table:
-- Event_Duration_Hours = DATEDIFF(Events[start_dt], Events[end_dt], HOUR)
